### ISSUE TITLE
showInfoWindow and NgMap.getMap

### ISSUE THREAD

**Issue by Nephidream** [allenhwkim/angularjs-google-maps#390]
To put some context, I have multiple instances of maps in my application, so when I want to use a map, I use the 
```
NgMap.getMap({id:'search_map'}).then(function(map) { ... }
```

I have a function that is called when I click on a marker:
```
$scope.clickMarker = function(){
  NgMap.getMap({id:'search_map'}).then(function(map) {
    map.showInfoWindow('click','bar',map.markers.foo);
  });
};
```

When I click and the said marker, I get the error:
```
TypeError: map.showInfoWindow is not a function
```

The map object seems to not be "populated" with the showInfoWindow function ?

For context, here is my HTML:

      <ng-map id="search_map" center="-25.363882,131.044922" default-style="true" zoom="4">
        <marker id="foo" on-click="clickMarker()" position="-25.363882,131.044922"></marker>
        <info-window id="bar" visible-on-marker="foo">
          <div ng-non-bindable>
            <div id="siteNotice"></div>
            <h1 class="firstHeading" id="firstHeading">Uluru</h1>
            <div id="bodyContent">
              <p>
                <b>Uluru</b>, also referred to as
                <b>Ayers Rock</b>, is a large sandstone rock formation in the southern part of the Northern Territory, central Australia. It lies 335&#160;km (208&#160;mi) south west of the nearest large town, Alice Springs; 450&#160;km (280&#160;mi) by road. Kata Tjuta and Uluru are the two major features of the Uluru - Kata Tjuta National Park. Uluru is sacred to the Pitjantjatjara and Yankunytjatjara, the Aboriginal people of the area. It has many springs, waterholes, rock caves and ancient paintings. Uluru is listed as a World Heritage Site.</p>
              <p>Attribution: Uluru,
                <a href="http://en.wikipedia.org/w/index.php?title=Uluru&oldid=297882194">
                  http://en.wikipedia.org/w/index.php?title=Uluru</a>
                (last visited June 22, 2009).</p>
            </div>
          </div>
        </info-window>
      </ng-map>

**Comment by arthurbragaa** [comment]
I'm having a similar problem when i click on a marker.
The same error is happening in this demo http://ngmap.github.io/#/infowindow_ng_click.html
    This is the error message:
    Error:Cannot read property 'showInfoWindow' of undefined 

And the code: 

```javascript
$scope.showCafeDetail = function(event, cafe){
    $scope.yelp.cafe = cafe;
    $scope.map.scope.showInfoWindow.apply(this, [event, 'marker-info']);
};
```

**Comment by allenhwkim** [comment]
There were some changes with infoWindow.

Please follow these examples;

 *  http://ngmap.github.io/#/infowindow_compile.html
 *  http://ngmap.github.io/#/infowindow_ng_click.html

**Comment by Nephidream** [comment]
Ok, I had 1.14.10 installed with the error 
```
TypeError: map.showInfoWindow is not a function
```

but I upgraded to 1.14.15 and now it works, thanks :)

**Comment by Jonfor** [comment]
I am currently on version 1.16.8 and I am getting this issue as well. showInfoWindow and hideInfoWindow are are both not functions apparently.

**Comment by vool** [comment]
Same issue here on 1.17.3

**Comment by leehk4** [comment]
It might be angularjs version related. I got that error when I used angular 1.2.29, but it went away when I upgraded to 1.4.5

**Comment by mkim871** [comment]
Same issue here on 1.17.3
any updates?

**Comment by frequencydesign** [comment]
I'm getting `Uncaught TypeError: Cannot read property 'showInfoWindow' of undefined` using 1.4.5

**Comment by frequencydesign** [comment]
This error may have been caused by not referencing the map instance. In my case, with I used:
```
NgMap.getMap().then(function(map) {
			vm.map = map;
		});
```
I needed to grab the map I wanted to reference. I added the id attribute from the DOM node as a parameter inside of the getMap() method. So:

```
NgMap.getMap("map_canvas").then(function(map) {
			vm.map = map;
		});
```

**Comment by Esya** [comment]
I'm having this issue too not sure why this is closed. On the latest version 1.17.8, with Angular 1.5.3 running with Ionic as well.

The "map" object just does not have a showInfoWindow function. 

[Codepen here](http://codepen.io/esya/pen/mOyzqz) open your console and look at the console.log of map. (I picked this codepen example somewhere and adapted it, I use NgMap.getMap on my side, and get the exact same type of object, with no showInfoWindow function)

**Comment by allenhwkim** [comment]
@Eysa, you do not have `info-window` directive, which adds `showInfoWindow` to `map` object.

**Comment by patrykboch** [comment]
The same issue in 1.17.8
 my code:

```
    NgMap.getMap('mapDemo').then (map) ->
      $scope.map = map
      for pointer in markers
        latLng = new (google.maps.LatLng)(pointer.latitude, pointer.longitude)
        marker = new (google.maps.Marker)(position: latLng)
        google.maps.event.addListener marker, 'click', ->
          $scope.selectedMarker = marker
          $scope.map.showInfoWindow 'myInfoWindow', this
        $scope.dynMarkers.push marker
      options = imagePath: 'https://cdn.rawgit.com/googlemaps/js-marker-clusterer/gh-pages/images/m'
      $scope.markerClusterer = new MarkerClusterer(map, $scope.dynMarkers, options, {})

```
_$scope.map.showInfoWindow is not a function_

**Comment by patrykboch** [comment]
LOL

**Comment by WillGeller** [comment]
Is there a method added to map object to hide **all** infowindows? I am having issues white on-mouseout not triggering if you mouse over a tight cluster of markers some get left window not calling $ctrl.map.hideInfoWindow(windowId);


`<marker ng-repeat="marker in myMarkerStore.markers track by $index" id="{{marker.uid}}" position="{{marker.lat + ', ' + marker.long}}"
            on-click="$parent.$parent.$ctrl.setOutputData(marker.watchList);" on-mouseover="$parent.$parent.$ctrl.showInfoWindow(marker.uid+'InfoWindow', marker.uid);" on-mouseout="$parent.$parent.$ctrl.hideInfoWindow(marker.uid+'InfoWindow', marker.uid);" 
            icon="{url: '{{ (!markersBinaryPoints[$index] || !marker.markerIconFalse) ? marker.markerIcon : markersBinaryPoints[$index].value ? marker.markerIcon : marker.markerIconFalse}}'}"></marker>
            <info-window ng-repeat="marker in myMarkerStore.markers" id="{{marker.uid}}InfoWindow">
                <div>
                    <h5>Well Name: <strong>{{marker.name}}</strong></h5>
                    <h5>Location: <strong>{{(marker.lat | number:4) + '° lat, ' + (marker.long | number:4) + '° long'}}</strong></h5>
                    <h5>Watch List: <strong>{{marker.watchList.name || 'Undefined'}}</strong></h5>
                    <h5>Info: <strong>{{marker.info || 'Undefined'}}</strong></h5>
                </div>
            </info-window>`
`$ctrl.toggleInfoWindow = function(e, windowId, markerId) {
            // console.log('toggle called', e, windowId, markerId);
            if (!$ctrl.infoWindowCache[windowId]) {
                $ctrl.map.showInfoWindow(windowId, markerId);
                $ctrl.infoWindowCache[windowId] = true;
            }
            else {
                $ctrl.map.hideInfoWindow(windowId);
                $ctrl.infoWindowCache[windowId] = false;
            }
        };

        $ctrl.showInfoWindow = function(e, windowId, markerId) {
            $ctrl.map.showInfoWindow(windowId, markerId);
        };

        $ctrl.hideInfoWindow = function(e, windowId, markerId) {
            $ctrl.map.hideInfoWindow(windowId);
        };

        $ctrl.hideAllInfoWindows = function(e) {
            // $ctrl.map.hideAllInfoWindows();
        };`

**Comment by WillGeller** [comment]
Found a work around with:



```
        $ctrl.showInfoWindow = function(e, windowId, markerId) {
            $ctrl.map.showInfoWindow(windowId, markerId);

            $ctrl.allInfoWindows.push(windowId);
        };

        $ctrl.hideInfoWindow = function(e, windowId) {
            $ctrl.map.hideInfoWindow(windowId);
        };

        $ctrl.hideAllInfoWindows = function(e) {
            $ctrl.allInfoWindows.forEach(function(windowId) {
                $ctrl.map.hideInfoWindow(windowId);
            });
        };
```

**Comment by nicolas15000** [comment]
Hello, me too I display 2 maps at the same time on my screens, and on-mouseover="" works only on one Map, the other show  this : 
TypeError: a is undefined

  please help.
